# TensorFlow 1.x

## Installing TensorFlow 1.x

In [1]:
!pip install tensorflow==1.13.1

     |████████████████████████████████| 92.5MB 38.0MB/s 
     |████████████████████████████████| 368kB 56.6MB/s 
     |████████████████████████████████| 3.2MB 57.4MB/s 
  Found existing installation: tensorflow-estimator 1.14.0
    Uninstalling tensorflow-estimator-1.14.0:
      Successfully uninstalled tensorflow-estimator-1.14.0
  Found existing installation: tensorboard 1.14.0
    Uninstalling tensorboard-1.14.0:
      Successfully uninstalled tensorboard-1.14.0
  Found existing installation: tensorflow 1.14.0
    Uninstalling tensorflow-1.14.0:
      Successfully uninstalled tensorflow-1.14.0


In [0]:
import tensorflow as tf

In [3]:
tf.__version__

'1.13.1'

### Constant

#### Defining Constant

In [0]:
tensor_1 = tf.constant([[3,8],[6,4]])

In [6]:
tensor_1

<tf.Tensor 'Const_1:0' shape=(2, 2) dtype=int32>

**All methods and attributes availble for Tensor Flow Constant**
![Tensorflow constants methods](https://github.com/interviewBubble/TensorFlow-2.0-tutorial/raw/master/media/images/Tensorflow%20constants%20methods.png)

Let's see few of them...

In [12]:
tensor_1.shape

TensorShape([Dimension(2), Dimension(2)])

In [14]:
tensor_1.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [17]:
tensor_1.name

'Const_1:0'

In [18]:
tensor_1.dtype

tf.int32

In [20]:
tensor_1.graph

In [21]:
tensor_1.eval()

ValueError: ignored

#### Getting Value of a constant


Methods and Attributes available on Session class
![Methods and Attributes available on Session class](https://github.com/interviewBubble/TensorFlow-2.0-tutorial/raw/master/media/images/methods%20in%20session%20class.png)


In [0]:
session = tf.Session()

In [26]:
session.list_devices()

[_DeviceAttributes(/job:localhost/replica:0/task:0/device:CPU:0, CPU, 268435456, 12746602636946716634),
 _DeviceAttributes(/job:localhost/replica:0/task:0/device:XLA_CPU:0, XLA_CPU, 17179869184, 7737566084416235221)]

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_1_value = session.run(tensor_1)

In [33]:
tensor_1_value

array([[3, 8],
       [6, 4]], dtype=int32)

### Variable

#### Defining a Variable

In [0]:
tensor_var_1 = tf.Variable([[2,12], [43,81]])

In [37]:
tensor_var_1.shape

TensorShape([Dimension(2), Dimension(2)])

In [38]:
tensor_var_1.eval()

ValueError: ignored

#### Getting Value of a Variable

In [0]:
session = tf.Session()

In [0]:
session.run(tf.global_variables_initializer())

In [0]:
tensor_var_1_value = session.run(tensor_var_1)

In [42]:
tensor_var_1_value

array([[ 2, 12],
       [43, 81]], dtype=int32)

## TensorFlow 2.0

## Installing TensorFlow 2.x

In [43]:
 !pip install tensorflow==2.0.0-rc1 

     |████████████████████████████████| 86.3MB 413kB/s 
     |████████████████████████████████| 501kB 55.9MB/s 
     |████████████████████████████████| 4.3MB 58.3MB/s 
  Found existing installation: tensorflow 1.13.1
    Uninstalling tensorflow-1.13.1:
      Successfully uninstalled tensorflow-1.13.1


In [0]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0-rc1'

### Constant

#### Defining Constant

In [0]:
tensor_2 = tf.constant([[2,3],[5,1]])

In [12]:
tensor_2.shape

TensorShape([2, 2])

In [9]:
tensor_2

<tf.Tensor: id=1, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [5, 1]], dtype=int32)>

In [10]:
tensor_2.eval()

NotImplementedError: ignored

#### Getting Value of Constant

In [11]:
tensor_2.numpy()

array([[2, 3],
       [5, 1]], dtype=int32)

In [0]:
import numpy as np

In [0]:
np_arr = np.array([[76,98],[5,9]])

In [0]:
np_tensor = tf.constant(np_arr)

In [16]:
np_tensor

<tf.Tensor: id=2, shape=(2, 2), dtype=int64, numpy=
array([[76, 98],
       [ 5,  9]])>

In [17]:
np_tensor.numpy()

array([[76, 98],
       [ 5,  9]])

### Variable

#### Defining a Variable

In [0]:
tensor_2_val = tf.Variable([[71,31], [32,65]])

In [19]:
tensor_2_val

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[71, 31],
       [32, 65]], dtype=int32)>

In [20]:
tensor_2_val.shape

TensorShape([2, 2])

#### Getting Value of a Variable

In [21]:
tensor_2_val.numpy()

array([[71, 31],
       [32, 65]], dtype=int32)

#### Changing a specific value in the variable

In [22]:
tensor_2_val[0,1]

<tf.Tensor: id=17, shape=(), dtype=int32, numpy=31>

In [23]:
tensor_2_val[0,1].assign(10)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[71, 10],
       [32, 65]], dtype=int32)>