## Operations with tensors

In [0]:
 !pip install tensorflow==2.0.0-rc1

In [0]:
import tensorflow as tf
tf.__version__

'2.0.0-rc1'

In [0]:
tensor = tf.constant([[5,3],[2,8]])

In [0]:
tensor.numpy()

array([[5, 3],
       [2, 8]], dtype=int32)

In [0]:
tensor + 4

<tf.Tensor: id=2, shape=(2, 2), dtype=int32, numpy=
array([[ 9,  7],
       [ 6, 12]], dtype=int32)>

In [0]:
tensor * 5

<tf.Tensor: id=4, shape=(2, 2), dtype=int32, numpy=
array([[25, 15],
       [10, 40]], dtype=int32)>

In [0]:
tensor - 10

<tf.Tensor: id=6, shape=(2, 2), dtype=int32, numpy=
array([[-5, -7],
       [-8, -2]], dtype=int32)>

In [0]:
import numpy as np

In [0]:
 np.square(tensor)

array([[25,  9],
       [ 4, 64]], dtype=int32)

In [0]:
np.sqrt(tensor)

array([[2.23606798, 1.73205081],
       [1.41421356, 2.82842712]])

In [0]:
another = tf.constant([[2,1],[5,21]])

In [0]:
another.numpy()

array([[ 2,  1],
       [ 5, 21]], dtype=int32)

In [0]:
tensor.numpy()

array([[5, 3],
       [2, 8]], dtype=int32)

In [0]:
np.dot(another, tensor)

array([[ 12,  14],
       [ 67, 183]], dtype=int32)